### PR TITLE
Added Markdown output template

### PR DESCRIPTION
**Pull request by simon-michaud**
I created a markdown template that works against your psDoc script.

### CODE REVIEW

**Comment by ChaseFlorell** [comment]
cool, I don't have time to run a test right now, any chance you can post a Screenshot of the resulting HTML?

**Comment by simon-michaud** [comment]
Hmm, sorry it generates a Mardown output not a html output, so it depends on your MD renderer but here goes with GitHubs one...

# 

# Module FileSystem-Utils

## Check-IsSymbolicLink

### Syntax

Check-IsSymbolicLink [-Path] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## New-FolderIfNotExists

### Synopsis

Creates a new folder if it does not already exists.

### Syntax

New-FolderIfNotExists [[-Folder] &lt;String&gt;] [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Folder</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td></td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    New-FolderIfNotExists ".\tmp"
```

**EXAMPLE 2**

```
    New-FolderIfNotExists "..\..\tmp"
```

**EXAMPLE 3**

```
    New-FolderIfNotExists "c:\data\tmp"
```

## New-SymbolicLink

### Syntax

New-SymbolicLink [-OriginalPath] &lt;Object&gt; [-MirroredPath] &lt;Object&gt; [[-Type] &lt;Object&gt;] [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>MirroredPath</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>OriginalPath</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>Type</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## Remove-LongDirectoryStructure

### Syntax

Remove-LongDirectoryStructure is a function which delete everything under a folder even if folders/files are longuer than 260 characters.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The relative of absolute path to the root of the folder hierachy to be deleted</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Inputs
- String
  ### Outputs
- None
  
  ### Examples
  
  **EXAMPLE 1**
  
  ```
  Remove-LongDirectoryStructure -Path C:\WebSite\Cache
  ```

**EXAMPLE 2**

```
    Remove-LongDirectoryStructure -Path Sitecore\Items
```

## Remove-SymbolicLink

### Syntax

Remove-SymbolicLink [-Link] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Link</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## Resolve-AbsolutePath

### Synopsis

Returns the absolute path of a folder of file recieved as parameter (absolute or relative) wether it exists or not on disk.

### Syntax

Resolve-AbsolutePath [-Path] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The path tat should be resolved as an absolute path. it can contain ".", "..", "..\..", etc. meta-folder and will be <br>resolved correctly.</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    Resolve-AbsolutePath -Path "C:\windows\system32\drivers\..\.."
```

Will return "C:\Windows"
**EXAMPLE 2**

```
    Resolve-AbsolutePath -Path "C:\windows\system32\"
```

Will return "C:\Windows\system32"
**EXAMPLE 3**

```
    Resolve-AbsolutePath -Path "drivers"
```

Will return "C:\windows\system32\drivers", assuming we were in th folder "C:\Windows\system32" when the call was made
**EXAMPLE 4**

```
    Resolve-AbsolutePath -Path "./drivers"
```

Will return "C:\windows\system32\drivers", assuming we were in th folder "C:\Windows\system32" when the call was made

## Touch

### Syntax

Touch upates the la stModified date of a file to Now.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>File</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The relative or absolute path of the file</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    Touch myfile.txt
```

**EXAMPLE 2**

```
    Touch ../myotherfile.txt
```

**EXAMPLE 3**

```
    Touch c:\myotherfile.txt
```

## Unzip-File

### Syntax

Unzip-File is a function which extracts the contents of a zip file.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>File</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The complete path and name of the zip file in this format: C:\zipfiles\myzipfile.zip</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>Destination</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The destination folder to extract the contents of the zip file to. If a path is no specified, the current path <br>is used.</td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg">(Get-Location).Path</td>
        </tr>
        <tr>
            <td><nobr>ForceCOM</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>Switch parameter to force the use of COM for the extraction even if the .NET Framework 4.5 is present.</td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg">False</td>
        </tr>
    </tbody>
</table>            

### Inputs
- String
  ### Outputs
- None
  
  ### Note
  
  Sourece: https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Function-to-727d6200  
  Author:  Mike F Robbins 
  Website: http://mikefrobbins.com 
  Twitter: @mikefrobbins
  
  ### Examples
  
  **EXAMPLE 1**
  
  ```
  Unzip-File -File C:\zipfiles\AdventureWorks2012_Database.zip -Destination C:\databases\
  ```

**EXAMPLE 2**

```
    Unzip-File -File C:\zipfiles\AdventureWorks2012_Database.zip -Destination C:\databases\ -ForceCOM
```

**EXAMPLE 3**

```
    'C:\zipfiles\AdventureWorks2012_Database.zip' | Unzip-File
```

**EXAMPLE 4**

```
    Get-ChildItem -Path C:\zipfiles | ForEach-Object {$_.fullname | Unzip-File -Destination C:\databases}
```

**Comment by ChaseFlorell** [comment]
Right, I understand that. The rendering looks good except for the "Inputs" section.

Upon a quick glance at the template, it seems to be missing the if check 

```
    # HTML Example
    $inputTypes = $(FixString($_.inputTypes  | out-string))
    if ($inputTypes.Length -gt 0 -and -not $inputTypes.Contains('inputType')) {
@"
                        <div>
                            <h3> Inputs </h3>
                            <p>The input type is the type of the objects that you can pipe to the cmdlet.</p>
                            <ul><li>$inputTypes</li></ul>
                        </div>
"@
    }
```

Basically, the template can get screwed up when powershell queries an object that isn't there.

**Comment by simon-michaud** [comment]
Actually it was missing blank lines after the unordered list item in Input, output and Notes sections... fixed

# FileSystem-Utils

## Check-IsSymbolicLink

### Syntax

Check-IsSymbolicLink [-Path] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## New-FolderIfNotExists

### Synopsis

Creates a new folder if it does not already exists.

### Syntax

New-FolderIfNotExists [[-Folder] &lt;String&gt;] [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Folder</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td></td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    New-FolderIfNotExists ".\tmp"
```

**EXAMPLE 2**

```
    New-FolderIfNotExists "..\..\tmp"
```

**EXAMPLE 3**

```
    New-FolderIfNotExists "c:\data\tmp"
```

## New-SymbolicLink

### Syntax

New-SymbolicLink [-OriginalPath] &lt;Object&gt; [-MirroredPath] &lt;Object&gt; [[-Type] &lt;Object&gt;] [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>MirroredPath</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>OriginalPath</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>Type</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## Remove-LongDirectoryStructure

### Syntax

Remove-LongDirectoryStructure is a function which delete everything under a folder even if folders/files are longuer than 260 characters.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The relative of absolute path to the root of the folder hierachy to be deleted</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Inputs
- String

### Outputs
- None

### Examples

**EXAMPLE 1**

```
    Remove-LongDirectoryStructure -Path C:\WebSite\Cache
```

**EXAMPLE 2**

```
    Remove-LongDirectoryStructure -Path Sitecore\Items
```

## Remove-SymbolicLink

### Syntax

Remove-SymbolicLink [-Link] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Link</nobr></td>
            <td class="visible-lg visible-md">None</td>
            <td></td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

## Resolve-AbsolutePath

### Synopsis

Returns the absolute path of a folder of file recieved as parameter (absolute or relative) wether it exists or not on disk.

### Syntax

Resolve-AbsolutePath [-Path] &lt;Object&gt; [&lt;CommonParameters&gt;]

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>Path</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The path tat should be resolved as an absolute path. it can contain ".", "..", "..\..", etc. meta-folder and will be <br>resolved correctly.</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    Resolve-AbsolutePath -Path "C:\windows\system32\drivers\..\.."
```

Will return "C:\Windows"
**EXAMPLE 2**

```
    Resolve-AbsolutePath -Path "C:\windows\system32\"
```

Will return "C:\Windows\system32"
**EXAMPLE 3**

```
    Resolve-AbsolutePath -Path "drivers"
```

Will return "C:\windows\system32\drivers", assuming we were in th folder "C:\Windows\system32" when the call was made
**EXAMPLE 4**

```
    Resolve-AbsolutePath -Path "./drivers"
```

Will return "C:\windows\system32\drivers", assuming we were in th folder "C:\Windows\system32" when the call was made

## Touch

### Syntax

Touch upates the la stModified date of a file to Now.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>File</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The relative or absolute path of the file</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
    </tbody>
</table>            

### Examples

**EXAMPLE 1**

```
    Touch myfile.txt
```

**EXAMPLE 2**

```
    Touch ../myotherfile.txt
```

**EXAMPLE 3**

```
    Touch c:\myotherfile.txt
```

## Unzip-File

### Syntax

Unzip-File is a function which extracts the contents of a zip file.

### Parameters

<table class="table table-striped table-bordered table-condensed visible-on">
    <thead>
        <tr>
            <th>Name</th>
            <th class="visible-lg visible-md">Alias</th>
            <th>Description</th>
            <th class="visible-lg visible-md">Required?</th>
            <th class="visible-lg">Pipeline Input</th>
            <th class="visible-lg">Default Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><nobr>File</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The complete path and name of the zip file in this format: C:\zipfiles\myzipfile.zip</td>
            <td class="visible-lg visible-md">true</td>
            <td class="visible-lg">true (ByValue)</td>
            <td class="visible-lg"></td>
        </tr>
        <tr>
            <td><nobr>Destination</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>The destination folder to extract the contents of the zip file to. If a path is no specified, the current path <br>is used.</td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg">(Get-Location).Path</td>
        </tr>
        <tr>
            <td><nobr>ForceCOM</nobr></td>
            <td class="visible-lg visible-md"></td>
            <td>Switch parameter to force the use of COM for the extraction even if the .NET Framework 4.5 is present.</td>
            <td class="visible-lg visible-md">false</td>
            <td class="visible-lg">false</td>
            <td class="visible-lg">False</td>
        </tr>
    </tbody>
</table>            

### Inputs
- String

### Outputs
- None

### Note

Sourece: https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Function-to-727d6200  
    Author:  Mike F Robbins 
    Website: http://mikefrobbins.com 
    Twitter: @mikefrobbins

### Examples

**EXAMPLE 1**

```
    Unzip-File -File C:\zipfiles\AdventureWorks2012_Database.zip -Destination C:\databases\
```

**EXAMPLE 2**

```
    Unzip-File -File C:\zipfiles\AdventureWorks2012_Database.zip -Destination C:\databases\ -ForceCOM
```

**EXAMPLE 3**

```
    'C:\zipfiles\AdventureWorks2012_Database.zip' | Unzip-File
```

**EXAMPLE 4**

```
    Get-ChildItem -Path C:\zipfiles | ForEach-Object {$_.fullname | Unzip-File -Destination C:\databases}
```

**Pull request merged**
